version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - 8000:8000
#    depends_on:
#      - nginx
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    # command: python3 manage.py runserver 0.0.0.0:8000
    # command: command: supervisord -n -c /etc/supervisor/conf.d/supervisord.conf 
  nginx:
    build:
      context: .
      dockerfile: server_image/Dockerfile
    volumes:
      - ./server_image:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - django
